/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        this.setExtendedState(menu_utama.MAXIMIZED_BOTH);
        
        execute();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu_sub = new javax.swing.JPanel();
        pnl_content = new javax.swing.JPanel();
        pnl_utama = new javax.swing.JPanel();
        jPanelGradient1 = new jpanelgradient.jPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pnl_sidebar.setPreferredSize(new java.awt.Dimension(250, 369));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        menu_sub.setBackground(new java.awt.Color(255, 255, 255));
        menu_sub.setLayout(new javax.swing.BoxLayout(menu_sub, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menu_sub);

        javax.swing.GroupLayout pnl_sidebarLayout = new javax.swing.GroupLayout(pnl_sidebar);
        pnl_sidebar.setLayout(pnl_sidebarLayout);
        pnl_sidebarLayout.setHorizontalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnl_sidebarLayout.setVerticalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_sidebar, java.awt.BorderLayout.LINE_START);

        pnl_content.setBackground(new java.awt.Color(255, 255, 255));
        pnl_content.setPreferredSize(new java.awt.Dimension(642, 90));

        pnl_utama.setBackground(new java.awt.Color(255, 255, 255));
        pnl_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnl_contentLayout = new javax.swing.GroupLayout(pnl_content);
        pnl_content.setLayout(pnl_contentLayout);
        pnl_contentLayout.setHorizontalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        pnl_contentLayout.setVerticalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_content, java.awt.BorderLayout.CENTER);

        jPanelGradient1.setColorStart(new java.awt.Color(0, 102, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Male User 2 (2).png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("NOT FOUND");

        javax.swing.GroupLayout jPanelGradient1Layout = new javax.swing.GroupLayout(jPanelGradient1);
        jPanelGradient1.setLayout(jPanelGradient1Layout);
        jPanelGradient1Layout.setHorizontalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGradient1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 674, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        jPanelGradient1Layout.setVerticalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelGradient1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pnl_utama.add(new Dashboard());
        pnl_utama.repaint();
        pnl_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private jpanelgradient.jPanelGradient jPanelGradient1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu_sub;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_sidebar;
    private javax.swing.JPanel pnl_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconDashboard = new ImageIcon(getClass().getResource("/picture/home.png"));
         menu_item menuDashboard    =new menu_item (iconDashboard, false,null,"Dashboard", new ActionListener() {
             
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Dashboard());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         
        ImageIcon iconMaster    =new ImageIcon(getClass().getResource("/picture/ms_master.png"));
        ImageIcon iconInputan1    =new ImageIcon(getClass().getResource("/picture/ms_master.png"));
        ImageIcon iconInputan2    =new ImageIcon(getClass().getResource("/picture/ms_master.png"));
        ImageIcon iconInputan3    =new ImageIcon(getClass().getResource("/picture/ms_master.png"));
        
         menu_item InputanBarang   =new menu_item (null, true, iconInputan1, "Input Barang",new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Input_Barang());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item InputanSuplier   =new menu_item (null, true, iconInputan2, "Input Suplier", new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Input_Suplier());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item InputanPengguna   =new menu_item (null, true, iconInputan3, "Input Pengguna", new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Input_Pengguna());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item menuMaster    =new menu_item (iconMaster, false,null,"Master",null,InputanBarang,InputanSuplier,InputanPengguna);
        
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/picture/transaksi.png"));
        ImageIcon iconPembelian = new ImageIcon(getClass().getResource("/picture/transaksi.png"));
        ImageIcon iconPenjualan = new ImageIcon(getClass().getResource("/picture/transaksi.png"));
         menu_item Pembelian   =new menu_item (null, true,iconPembelian,"Pembelian",new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Pembelian());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item Penjualan   =new menu_item (null, true,iconPenjualan,"Penjualan",new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Penjualan());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item menuTransaksi    =new menu_item (iconTransaksi, false,null,"Transaksi",null,Pembelian,Penjualan);
                 
        ImageIcon iconLaporan = new ImageIcon(getClass().getResource("/picture/laporan.png"));
        ImageIcon iconBarangMasuk = new ImageIcon(getClass().getResource("/picture/laporan.png"));
        ImageIcon iconBarangKeluar = new ImageIcon(getClass().getResource("/picture/laporan.png"));
        
         menu_item BarangMasuk   =new menu_item (null, true, iconBarangMasuk, "Data Barang Masuk", new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Barang_Masuk());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item BarangKeluar   =new menu_item (null, true, iconBarangKeluar, "Data Barang keluar",new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Barang_Keluar());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item menuLaporan    =new menu_item (iconLaporan, false,null,"Laporan",null,BarangMasuk,BarangKeluar);
         
         
        ImageIcon iconData = new ImageIcon(getClass().getResource("/picture/data.png"));
        ImageIcon iconSuplier = new ImageIcon(getClass().getResource("/picture/data.png"));
        ImageIcon iconPengguna = new ImageIcon(getClass().getResource("/picture/data.png"));
        ImageIcon iconBarang = new ImageIcon(getClass().getResource("/picture/data.png"));
        
        menu_item Barang  =new menu_item (null, true, iconBarang, "Data Barang", new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            pnl_utama.removeAll();
            pnl_utama.add(new Data_Barang());
            pnl_utama.repaint();
            pnl_utama.revalidate();
            }
        });
        
         menu_item Supplier   =new menu_item (null, true, iconSuplier, "Data Suplier", new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Data_Suplier());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item Pengguna   =new menu_item (null, true, iconPengguna, "Data Pengguna", new ActionListener() {
            public void actionPerformed(ActionEvent e){
            pnl_utama.removeAll();
            pnl_utama.add(new Data_Pengguna());
            pnl_utama.repaint();
            pnl_utama.revalidate();
         }
            });
         menu_item menuData    =new menu_item (iconData, false,null,"Data",null,Barang,Supplier, Pengguna);
         

        addMenu(menuDashboard, menuMaster, menuTransaksi, menuData, menuLaporan);
    }
    
    private void addMenu(menu_item... menu) {
        for (int i = 0; i < menu.length; i++) {
            menu_sub.add(menu[i]);
            ArrayList<menu_item> subMenu = menu[i].getSubMenu(); 
            for (menu_item m : subMenu) {
                addMenu(m);
            }
        }
    menu_sub.revalidate();
    }
}
